spring:
  r2dbc:
    url: r2dbc:h2:mem:///crediyadb;DB_CLOSE_DELAY=-1
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always